---
title: "RWorksheet3a in R"
author: "Keir G. Sumayo"
date: "2025-10-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###1. VECTORS
```{r}
LETTERS
```

```{r}
#a.
LET1 <- c(LETTERS[1:11])
LET1
```

```{r}
#b.
LET2 <- c(LETTERS[seq(1, 26, 2)])
LET2
```


```{r}
#c.
vowels <- LETTERS[LETTERS %in% c("A", "E", "I", "O", "U")]
vowels
```


```{r}
#d.
let1 <- c(letters[22:26])
let1
```


```{r}
#e.
let2 <- c(letters[16:23])
let2
```

###2. VECTORS
```{r}
#a.
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island", "Davao City")
```

```{r}
#b.
temp <- c(42, 39, 34, 34, 30, 27)
```

```{r}
#c.
table1 <- data.frame (
  city,
  temp
)
table1
```

```{r}
#d.
table2 <- data.frame (
  City = city,
  Temperature = temp
)
table2
```

```{r}
#e
str(table2)
```

```{r}
#f.
table2[3:4, ]
```


```{r}
#g.
highest_temp <- table2[1, 1]
highest_temp

lowest_temp <- table2[6, 2]
lowest_temp
```
###1. MATRIX (EXAMPLE)
```{r}
#row = 2
matrix(c(5,6,7,4,3,2,1,2,3,7,8,9), nrow = 2)
```

```{r}
#row = 3 and column = 2
matrix(data = c(3,4,5,6,7,8),nrow=3,ncol=2)
```

```{r}
#creating a diagonal matix where x value will always be 1
diag(1, nrow=6, ncol=5)

diag(6)
```

###2. MATRIX
```{r}
#a.
matrix_data <- matrix(c(1:8,11:14),3,4)
matrix_data
```

```{r}
#b.
product_matrix <- matrix_data * 2
product_matrix
```

```{r}
#c.
matrix_data[2, ]
```

```{r}
#d.
matrix_data[1:2, 3:4]
```

```{r}
#e.
matrix_data[3, 2:3]
```

```{r}
#f.
matrix_data[ ,4]
```

```{r}
#g.
rownames(matrix_data) <- c("isa", "dalawa", "tatlo")
colnames(matrix_data) <- c("uno", "dos", "tres", "quatro")
matrix_data
```

```{r}
#h.
dim(matrix_data) <- c(6,2)
matrix_data
```

###1. ARRAYS (EXAMPLE)
```{r}
#1.
#creates a two-dimensional array containing numbers from 1 to 24 that have 3 rows and
array_dta <- array(c(1:24), c(3,4,2))
array_dta
```

```{r}
#row, column, dimension
dim(array_dta)
```

```{r}
#checking for the number of elements
length(array_dta)
```

```{r}
vectorA <- c(1:24)
vectorA
```

```{r}
#2.
#creating an array
an_Array <- array(vectorA, dim = c(3,4,2))
an_Array

```
###2. ARRAYS
```{r}
array_data <- array(c(1:3, 6:9, 0, 3:5, 1))

#a.
array_a <- array(array_data, dim = c(2, 4, 3))
array_a
```

```{r}
#b.
str(array_a)
```


```{r}
#c.
dimnames(array_a)[[3]] <- c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array")

rownames(array_a) <- letters[1:2]
colnames(array_a) <- LETTERS[1:4]
array_a
```

